title: "Learning To Code"
author: "Robert Brittingham"
description: "Beginner Coder"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", titel: "Home", icon: home}
  - {file: "README.md", titel: "Projects", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:robert.github.io"}
  - {title: Github, icon: github, url: "https://robert.github.io"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/channel/UCvDTJ9uwaeBUJtAABaIhn-g"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
